services:
  vernemq:
    image: vernemq/vernemq:latest
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes" # obligatoire pour l'image officielle
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on" # dev only: no authentication
    ports:
      - "1883:1883" # MQTT
      - "8888:8888" # page HTTP status

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" # Redis

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: bms
      POSTGRES_PASSWORD: bms
      POSTGRES_DB: bms
    ports:
      - "5432:5432" # PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql #named volume for persistent data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro #file, mounted as read-only, to initialize the database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bms -d bms"]
      interval: 5s
      retries: 20

  simulator:
    build: ./simulator                 # construit l'image à partir de ./simulator/Dockerfile
    environment:
      MQTT_HOST: vernemq               # nom du service : dans Docker, "localhost" serait le conteneur lui-même
      SCENARIO: ${SCENARIO:-normal}    # reprend la variable de ton terminal, "normal" par défaut
    depends_on: [vernemq]              # démarre après vernemq
    restart: unless-stopped            # relancé automatiquement s'il plante

  normalizer:
    build: ./normalizer
    environment:
      MQTT_URL: mqtt://vernemq:1883
      REDIS_URL: redis://redis:6379
    depends_on: [vernemq, redis]
    restart: unless-stopped
    
volumes:
  pgdata:
